name: Bug Report
description: Report a bug or unexpected behavior
title: 'bug: '
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting! Before submitting, please search [existing issues](https://github.com/sQVe/grove/issues).
        For usage questions, use [Discussions](https://github.com/sQVe/grove/discussions).

  - type: input
    attributes:
      label: Command
      description: The exact command that caused the issue
      placeholder: grove add feature-branch
    validations:
      required: true

  - type: input
    attributes:
      label: Version
      description: Output of `grove --version`
      placeholder: grove version 1.0.0
    validations:
      required: true

  - type: textarea
    attributes:
      label: What happened
      description: Describe the actual behavior
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behavior
      description: What you expected to happen
    validations:
      required: true

  - type: textarea
    attributes:
      label: Worktree list
      description: Output of `git worktree list` (if relevant)
      render: shell

  - type: textarea
    attributes:
      label: Environment
      description: OS, shell, git version, or other relevant details
      placeholder: |
        - OS: macOS 14.0
        - Shell: zsh
        - Git: 2.42.0

  - type: checkboxes
    attributes:
      label: Contribution
      options:
        - label: I'm willing to submit a pull request for this issue
