name: Feature Request
description: Suggest a new feature or improvement
title: 'feature: '
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: Problem
      description: What problem does this solve? What workflow are you trying to accomplish?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Proposed solution
      description: How should this work?

  - type: textarea
    attributes:
      label: Additional context
      description: Use cases, examples, or other details
